name: cd

on: [push, pull_request]

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        bun: [1]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Generate (Nuxt 4)
        # Nuxt 4 projects typically expose a `generate` script that calls `nuxi generate`.
        # Use bun to run the package script so project-level scripts work the same.
        run: bun run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist